// Generated by scripts/generate_dashboard_contract.py. Do not edit.
export const DASHBOARD_CONTRACT_VERSION = "1.0.0" as const;
export const DASHBOARD_SCHEMA_VERSION = 1 as const;

export interface CountryArticle {
  title: string;
  title_en: string | null;
  source: string;
  url: string | null;
  topic: string;
  escalation: string;
  published_date: string | null;
  processed_at: string | null;
}

export interface CountryIndexItem {
  country: string;
  slug: string;
  count: number;
}

export interface DailyCount {
  date: string;
  count: number;
}

export interface EntitySummary {
  total: number;
  top: Record<string, Array<RankedEntity>>;
}

export interface EscalationDistribution {
  escalation: Record<string, number>;
}

export interface MentionSummary {
  total: number;
  top: Record<string, Array<RankedMention>>;
}

export interface RankedEntity {
  name: string;
  count: number;
  surface_forms: Array<string>;
}

export interface RankedMention {
  name: string;
  count: number;
}

export interface RecentArticle {
  title: string;
  title_en: string | null;
  source: string;
  url: string | null;
  topic: string | null;
  escalation: string | null;
  country: string | null;
  ai_summary: string | null;
  processed_at: string | null;
  published_date: string | null;
}

export interface ReviewEvidence {
  mention_id: number;
  text: string;
  source: string;
  url: string | null;
  title: string;
}

export interface ReviewItem {
  id: number;
  object_type: string;
  score: number;
  threshold: number;
  distance: number;
  features: Record<string, number>;
  left: ReviewEvidence;
  right: ReviewEvidence;
}

export interface ReviewQueue {
  items: Array<ReviewItem>;
}

export interface SnapshotStats {
  total_raw: number;
  total_processed: number;
  sources: Record<string, number>;
}

export interface TopicCount {
  topic: string;
  count: number;
}

export interface TopicDistribution {
  topics: Array<TopicCount>;
}

export interface DashboardSnapshot {
  generated_at: string;
  schema_version: 1;
  stats: SnapshotStats;
  topics: TopicDistribution;
  escalation: EscalationDistribution;
  recent: Array<RecentArticle>;
  daily: Array<DailyCount>;
  mentions: MentionSummary;
  entities: EntitySummary;
  review_queue: ReviewQueue;
  countries: Array<CountryIndexItem>;
}

export interface CountrySnapshot {
  generated_at: string;
  schema_version: 1;
  country: string;
  slug: string;
  total: number;
  sources: Record<string, number>;
  topics: Array<TopicCount>;
  escalation: Record<string, number>;
  daily: Array<DailyCount>;
  articles: Array<CountryArticle>;
}
